version: "2.4"

services:
  jpyxd:
    container_name: jpyxd
    image: lcnem/jpyx:next
    ports:
      - 1317:1317
      - 9090:9090
      - 26656:26656
      - 26657:26657
    volumes:
      - ~/.jpyx:/root/.jpyx
    command: jpyxd start \
      --rpc.laddr=tcp://0.0.0.0:26657 \
      --api.enable=true \
      --api.address=tcp://0.0.0.0:1317 \
      --api.enabled-unsafe-cors=true
    network_mode: bridge
    networks:
      default:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
    restart: always
networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::1
