version: '3'

services:
  jpydnode0:
    container_name: jpydnode0
    image: "lcnem/jpyxnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-kvd.log}
    volumes:
      - ./build/linux:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  jpydnode1:
    container_name: jpydnode1
    image: "lcnem/jpyxnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-kvd.log}
    volumes:
      - ./build/linux:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  jpydnode2:
    container_name: jpydnode2
    image: "lcnem/jpyxnode"
    environment:
      - ID=2
      - LOG=${LOG:-kvd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build/linux:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  jpydnode3:
    container_name: jpydnode3
    image: "lcnem/jpyxnode"
    environment:
      - ID=3
      - LOG=${LOG:-kvd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build/linux:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
