version: "3"

services:
  jpyxd:
    container_name: jpyxd
    image: ghcr.io/ununifi/ununifid
    # ports:
    #   - 1317:1317
    #   - 9090:9090
    #   - 26656:26656
    #   - 26657:26657
    volumes:
      - ~/.jpyx:/root/.jpyx
    command: jpyxd start
    network_mode: host
    restart: always
