version: "2.4"

services:
  jpyxd:
    container_name: jpyxd
    image: lcnem/jpyx:next
    ports:
      - 1317:1317
      - 9090:9090
      - 26656:26656
      - 26657:26657
    volumes:
      - ~/.jpyx:/root/.jpyx
    command: jpyxd start \
      --rpc.laddr=tcp://0.0.0.0:26657 \
      --api.enable=true \
      --api.address=tcp://0.0.0.0:1317 \
      --api.enabled-unsafe-cors=true
    network_mode: host
    restart: always
