version: "3"

services:
  faucet-ubtc:
    container_name: faucet-ubtc
    image: ghcr.io/tendermint/faucet
    volumes:
      - ~/faucet/jpyxd:/usr/local/bin/jpyxd
      - ~/.jpyx:/root/.jpyx
    command: faucet --cli-name jpyxd --denoms ubtc --keyring-backend test --account-name faucet --port 7000 --credit-amount=100 --max-credit=99
    # ports:
    #   - 7000:7000
    network_mode: host
    restart: always
  faucet-ujcbn:
    container_name: faucet-ujcbn
    image: ghcr.io/tendermint/faucet
    volumes:
      - ~/faucet/jpyxd:/usr/local/bin/jpyxd
      - ~/.jpyx:/root/.jpyx
    command: faucet --cli-name jpyxd --denoms ujcbn --keyring-backend test --account-name faucet --port 7002 --credit-amount=2000000 --max-credit=1999999
    # ports:
    #   - 7002:7002
    network_mode: host
    restart: always
  faucet-jpyx:
    container_name: faucet-jpyx
    image: ghcr.io/tendermint/faucet
    volumes:
      - ~/faucet/jpyxd:/usr/local/bin/jpyxd
      - ~/.jpyx:/root/.jpyx
    command: faucet --cli-name jpyxd --denoms jpyx --keyring-backend test --account-name faucet --port 7004 --credit-amount=10 --max-credit=9
    # ports:
    #   - 7004:7004
    network_mode: host
    restart: always
  nginx:
    container_name: faucet-nginx
    image: nginx
    volumes:
      - ~/faucet/nginx.conf:/etc/nginx/nginx.conf
    # ports:
    #   - 8000:8000
    #   - 8002:8002
    #   - 8004:8004
    network_mode: host
    restart: always
